server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # 静态文件
    location / {
        root /usr/share/nginx/html;
        index pages/index.html;
        try_files $uri $uri/ /pages/index.html;
    }

    # 健康检查
    location /healthz {
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
    }
}
